### ISSUE TITLE
Upgrade Drupal Docker Images and Containers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#156]
Stop and remove drupal containers:

```sh
cd /docker/100-csis
docker-compose down
```

Manually trigger **incremental** [duplicity backup](https://github.com/clarity-h2020/docker-duplicity):

```sh
cd /docker/999-duplicity
docker-compose up
```
**Hint:** You can restore **the latest** backup-set with `docker-compose up -f restore.yml` to `./restore` directory.

Edit [Dockerfile](https://github.com/clarity-h2020/docker-drupal/blob/dev/drupal/Dockerfile) and change base image to [docker-drupal](https://hub.docker.com/_/drupal/) new version.
Example: `FROM drupal:8.9.1-apache`

**Hint:**  This does **not** update the existing CSIS Drupal Core, since the actual drupal system lives in a **host-mounted** `./drupal-data` volume! Therefore a **manual update** inside the new **running container** is required.

Edit [compose file](https://github.com/clarity-h2020/docker-drupal/blob/dev/docker-compose.yml) and change **custom csis-drupal image** tag, e.g. to `8.9.1-apache`, in order to be able to revert to the previous image:

```yml
  drupal:
    image: csis-drupal:8.9.1-apache
    build:
      context: ./drupal
```
Also upgrade [postgis/postgis](https://hub.docker.com/r/postgis/postgis/tags?page=1&name=10) image, if necessary.

```yml
  drupal-db:
    container_name: ${COMPOSE_PROJECT_NAME}-postgis
    image: postgis/postgis:10-3.0
```

Build our custom csis-drupal docker image:

```sh
cd /docker/100-csis
docker-compose build
```

Recreate containers:

```sh
docker-compose up -d --force-recreate --remove-orphans
```

sh into csis container and [Update Drupal Core and modules](https://github.com/clarity-h2020/docker-drupal/issues/148).

```sh
sudo su docker
docker exec -it --user 999 csis-drupal bash
# composer ...
```
