### ISSUE TITLE
Warning: Manage display can brick view mode

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/docker-drupal#34]
Managing the display of a view mode can 'brick' it under certain circumstances leaving the display unusable and uneditable. To reproduce just try to create a display like shown in the following example:

![grafik](https://user-images.githubusercontent.com/1788226/48185161-1a0e2180-e32c-11e8-97b3-f02da0760eff.png)

Arranging the different groups (tabs, tab) and fields and getting them in the right order is a challenge on its own! Drag & Drop behaviour seems the be unpredictable so that the groups and fields don't appear in the hierarchy where you've put them. Even worse, what you see isn't always what you get! So after saving the view mode the arrangement of fields and groups may still be different than what is shown on the screen:

![drupal-havok](https://user-images.githubusercontent.com/1788226/48201123-8b1bfc00-e361-11e8-97b0-cd5b70947e5a.gif)

This may lead to a situation where a container group (tabs) is put below a contained groups (tab) without the user even noticing. Such a situation may lead to some kind of endless loop rendering the display 'bricked'. An attempt to change the display will then yield the following error:

**Fatal error: Maximum execution time of 30 seconds exceeded in /app/web/core/modules/field_ui/src/Element/[FieldUiTable.php on line 64](https://github.com/drupal/drupal/blob/646584b3f718897179589f4f014531e3d9365331/core/modules/field_ui/src/Element/FieldUiTable.php#L64)**

@patrickkaleta @fgeyer16 

Do you see any change to repair / recreate the following display: `/admin/structure/types/manage/gl_step/display/sce`
E.g. exporting with drush, changing the group order and re-importing again?

**Comment by p-a-s-c-a-l** [comment]
To restore the unresponsive display view, change faulty `core.entity_view_display.node.gl_step.sce.yml`, remove group_preview child of group_preview group and import with `drush cim`.

```yml
field_group:
    group_preview:
      children:
        - group_prototype
      parent_name: group_prototype
      weight: 0
      format_type: tabs
      format_settings:
        id: ''
        classes: ''
        direction: vertical
      label: Preview
    group_prototype:
      children:
        - group_preview
        - field_external_app
      parent_name: group_preview
      weight: 1
      format_type: tab
      format_settings:
        id: ''
        classes: ''
        formatter: open
        description: ''
      label: Prototype
```
